### PR TITLE
flesh out the polar domain details.

### PR DESCRIPTION
**Pull request by chrismattmann**

### CODE REVIEW

**Comment by chrismattmann** [comment]
@graceyang99 @isoboroff @johnrfrank can the website be updated with this PR? I fleshed out the details.

**Comment by graceyang99** [comment]
see it, Thanks!

Will update it

On Mon, Nov 9, 2015 at 10:10 AM, Chris Mattmann notifications@github.com
wrote:

> @graceyang99 https://github.com/graceyang99 @isoboroff
> https://github.com/isoboroff @johnrfrank https://github.com/johnrfrank
> can the website be updated with this PR? I fleshed out the details.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/trec-dd/trec-dd.org/pull/7#issuecomment-155091205.

## 

Cheers
Grace Hui Yang

**Comment by chrismattmann** [comment]
thanks @graceyang99 you rule

**Comment by chrismattmann** [comment]
@graceyang99 ping please ask one of the students to update the website with this PR thanks

**Comment by chrismattmann** [comment]
@isoboroff @graceyang99 can someone please deploy this to the website? cc @johnrfrank

**Pull request merged**
